- id: my_unique_id0
  alias: Appletv notifier
  trigger:
  - platform: time
    minutes: /5
    seconds: 5
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: media_player.apple_tv
      state: playing
    - condition: state
      entity_id: input_boolean.appletv_alarm
      state: 'on'
    - condition: template
      value_template: '{{ states.sensor.appletv_today.state | float > 2 }}'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.stuelampe
- id: my_unique_id1
  alias: Turn on outside lighting when the sun gets dim
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
    service: scene.turn_on
    entity_id: scene.outside_lighting
- id: my_unique_id2
  alias: Turn off outside lighting when the sun gets bright
  trigger:
  - above: '3.5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  action:
  - entity_id: scene.outside_lighting_off
    service: scene.turn_on
  - data: {The sun is up! Turning off external lights!}
    service: notify.prowl
- id: my_unique_id
  alias: Turn a few lights on when the sun gets dim
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
  - service: scene.turn_on
    entity_id: scene.background_lights
- id: my_unique_id3
  alias: Turn more lights on as the sun gets dimmer
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.5
  action:
    service: scene.turn_on
    entity_id: switch.inne
