- alias: Appletv notifier
  trigger:
    - platform: time
      minutes: '/5'
      seconds: 05
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: media_player.apple_tv
      state: 'playing'
    # If Notifier = on
    - condition:  state
      entity_id: input_boolean.appletv_alarm
      state: 'on'
    - condition: template
      value_template: '{{ states.sensor.appletv_today.state | float > 2 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.stuelampe

- alias: 'Turn on outside lighting when the sun gets dim'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
    service: scene.turn_on
    entity_id: scene.outside_lighting

- alias: 'Turn off outside lighting when the sun gets bright'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  action:
    service: scene.turn_on
    entity_id: scene.outside_lighting_off

- alias: 'Turn a few lights on when the sun gets dim'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
    - service: scene.turn_on
      entity_id: scene.background_lights
    - service: homeassistant.turn_on
      entity_id: switch.ute
- alias: 'Turn more lights on as the sun gets dimmer'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.5
  action:
    service: scene.turn_on
    entity_id: switch.inne
